version: '3.9'

services:
  php-fpm-nginx:
    image: vangoda/php-fpm-alpine:0.11
    volumes:
      - ./config-custom/nginx.conf:/etc/nginx/nginx.conf
      - ./config-custom/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    # ports:
    #   - "80:80"
    environment:
      - VIRTUAL_HOST=test.local
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true